#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class MySQL_XeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    #endregion
		
		public MySQL_XeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySQL_XeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySQL_XeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySQL_XeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private string _TenXe;
		
		private string _MaLoaiXe;
		
		private string _MaNSX;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private System.Nullable<int> _GiaBan;
		
		private string _MaKho;
		
		private System.Nullable<int> _BaoHanh;
		
		private System.Nullable<int> _SoLuong;
		
		private string _SoKhung;
		
		private string _SoMay;
		
		private string _Mau;
		
		private string _LoaiDongCo;
		
		private string _BoTriXyLanh;
		
		private string _DungTichXyLanh;
		
		private string _KhoiDong;
		
		private string _BinhXang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnMaLoaiXeChanging(string value);
    partial void OnMaLoaiXeChanged();
    partial void OnMaNSXChanging(string value);
    partial void OnMaNSXChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnGiaBanChanging(System.Nullable<int> value);
    partial void OnGiaBanChanged();
    partial void OnMaKhoChanging(string value);
    partial void OnMaKhoChanged();
    partial void OnBaoHanhChanging(System.Nullable<int> value);
    partial void OnBaoHanhChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnSoKhungChanging(string value);
    partial void OnSoKhungChanged();
    partial void OnSoMayChanging(string value);
    partial void OnSoMayChanged();
    partial void OnMauChanging(string value);
    partial void OnMauChanged();
    partial void OnLoaiDongCoChanging(string value);
    partial void OnLoaiDongCoChanged();
    partial void OnBoTriXyLanhChanging(string value);
    partial void OnBoTriXyLanhChanged();
    partial void OnDungTichXyLanhChanging(string value);
    partial void OnDungTichXyLanhChanged();
    partial void OnKhoiDongChanging(string value);
    partial void OnKhoiDongChanged();
    partial void OnBinhXangChanging(string value);
    partial void OnBinhXangChanged();
    #endregion
		
		public Xe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", DbType="VarChar(10)")]
		public string MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", DbType="VarChar(10)")]
		public string MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int")]
		public System.Nullable<int> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKho", DbType="VarChar(10)")]
		public string MaKho
		{
			get
			{
				return this._MaKho;
			}
			set
			{
				if ((this._MaKho != value))
				{
					this.OnMaKhoChanging(value);
					this.SendPropertyChanging();
					this._MaKho = value;
					this.SendPropertyChanged("MaKho");
					this.OnMaKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="Int")]
		public System.Nullable<int> BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoKhung", DbType="Char(10)")]
		public string SoKhung
		{
			get
			{
				return this._SoKhung;
			}
			set
			{
				if ((this._SoKhung != value))
				{
					this.OnSoKhungChanging(value);
					this.SendPropertyChanging();
					this._SoKhung = value;
					this.SendPropertyChanged("SoKhung");
					this.OnSoKhungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoMay", DbType="Char(10)")]
		public string SoMay
		{
			get
			{
				return this._SoMay;
			}
			set
			{
				if ((this._SoMay != value))
				{
					this.OnSoMayChanging(value);
					this.SendPropertyChanging();
					this._SoMay = value;
					this.SendPropertyChanged("SoMay");
					this.OnSoMayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="NVarChar(10)")]
		public string Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDongCo", DbType="NVarChar(50)")]
		public string LoaiDongCo
		{
			get
			{
				return this._LoaiDongCo;
			}
			set
			{
				if ((this._LoaiDongCo != value))
				{
					this.OnLoaiDongCoChanging(value);
					this.SendPropertyChanging();
					this._LoaiDongCo = value;
					this.SendPropertyChanged("LoaiDongCo");
					this.OnLoaiDongCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoTriXyLanh", DbType="NVarChar(50)")]
		public string BoTriXyLanh
		{
			get
			{
				return this._BoTriXyLanh;
			}
			set
			{
				if ((this._BoTriXyLanh != value))
				{
					this.OnBoTriXyLanhChanging(value);
					this.SendPropertyChanging();
					this._BoTriXyLanh = value;
					this.SendPropertyChanged("BoTriXyLanh");
					this.OnBoTriXyLanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungTichXyLanh", DbType="NVarChar(50)")]
		public string DungTichXyLanh
		{
			get
			{
				return this._DungTichXyLanh;
			}
			set
			{
				if ((this._DungTichXyLanh != value))
				{
					this.OnDungTichXyLanhChanging(value);
					this.SendPropertyChanging();
					this._DungTichXyLanh = value;
					this.SendPropertyChanged("DungTichXyLanh");
					this.OnDungTichXyLanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiDong", DbType="NVarChar(50)")]
		public string KhoiDong
		{
			get
			{
				return this._KhoiDong;
			}
			set
			{
				if ((this._KhoiDong != value))
				{
					this.OnKhoiDongChanging(value);
					this.SendPropertyChanging();
					this._KhoiDong = value;
					this.SendPropertyChanged("KhoiDong");
					this.OnKhoiDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinhXang", DbType="NVarChar(50)")]
		public string BinhXang
		{
			get
			{
				return this._BinhXang;
			}
			set
			{
				if ((this._BinhXang != value))
				{
					this.OnBinhXangChanging(value);
					this.SendPropertyChanging();
					this._BinhXang = value;
					this.SendPropertyChanged("BinhXang");
					this.OnBinhXangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
